import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

import { createClient } from '@/lib/supabase/server'
import { getDocument, getUserByAuthId } from '@/lib/supabase/queries'

import type { DocumentStatus } from '@/types/database'

interface RouteContext {
  params: Promise<{ id: string }>
}

const STATUS_LABELS: Record<DocumentStatus, string> = {
  draft: 'Draft',
  review: 'In Review',
  approved: 'Approved',
}

export async function GET(
  request: NextRequest,
  context: RouteContext
): Promise<NextResponse> {
  const { id } = await context.params
  const supabase = await createClient()
  const { data: { user: authUser } } = await supabase.auth.getUser()

  if (!authUser) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: dbUser } = await getUserByAuthId(supabase, authUser.id)
  if (!dbUser?.organization_id) {
    return NextResponse.json({ error: 'User has no organization' }, { status: 400 })
  }

  const { data: document, error } = await getDocument(supabase, id)

  if (error || !document) {
    return NextResponse.json({ error: 'Document not found' }, { status: 404 })
  }

  if (document.organization_id !== dbUser.organization_id) {
    return NextResponse.json({ error: 'Access denied' }, { status: 403 })
  }

  // Generate PDF
  const chunks: Buffer[] = []

  const pdf = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: document.title,
      Author: 'ClarionAI',
      Subject: 'EU AI Act Compliance Document',
    },
  })

  pdf.on('data', (chunk: Buffer) => chunks.push(chunk))

  // Title
  pdf.fontSize(24).font('Helvetica-Bold').text(document.title, { align: 'left' })
  pdf.moveDown(0.5)

  // Metadata
  pdf.fontSize(10).font('Helvetica').fillColor('#666666')
  pdf.text(`AI System: ${document.content.aiSystemName}`)
  pdf.text(`Organization: ${document.content.organizationName}`)
  pdf.text(`Version: ${document.version} | Status: ${STATUS_LABELS[document.status]}`)
  pdf.text(`Generated: ${new Date(document.created_at).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })}`)
  pdf.moveDown()

  // Divider
  pdf.strokeColor('#cccccc').lineWidth(1)
  pdf.moveTo(50, pdf.y).lineTo(545, pdf.y).stroke()
  pdf.moveDown()

  pdf.fillColor('#000000')

  // Sections
  for (const section of document.content.sections) {
    // Check if we need a new page
    if (pdf.y > 700) {
      pdf.addPage()
    }

    // Section title
    pdf.fontSize(14).font('Helvetica-Bold')
    pdf.text(`${section.title}`, { continued: false })
    pdf.fontSize(9).font('Helvetica').fillColor('#666666')
    pdf.text(section.articleReference)
    pdf.moveDown(0.3)

    // Section content
    pdf.fontSize(10).font('Helvetica').fillColor('#333333')

    // Process content - handle basic markdown-like formatting
    const lines = section.content.split('\n')
    for (const line of lines) {
      if (pdf.y > 750) {
        pdf.addPage()
      }

      const trimmedLine = line.trim()
      if (!trimmedLine) {
        pdf.moveDown(0.3)
        continue
      }

      // Bold headers (text wrapped in **)
      if (trimmedLine.startsWith('**') && trimmedLine.endsWith('**')) {
        pdf.font('Helvetica-Bold').text(trimmedLine.replace(/\*\*/g, ''))
        pdf.font('Helvetica')
      }
      // Bullet points
      else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('• ')) {
        pdf.text(`  •  ${trimmedLine.replace(/^[-•]\s*/, '')}`, { indent: 10 })
      }
      // Numbered lists
      else if (/^\d+\.\s/.test(trimmedLine)) {
        pdf.text(`  ${trimmedLine}`, { indent: 10 })
      }
      // Regular text
      else {
        pdf.text(trimmedLine)
      }
    }

    pdf.moveDown()
    pdf.fillColor('#000000')
  }

  // Disclaimer
  if (pdf.y > 680) {
    pdf.addPage()
  }

  pdf.moveDown()
  pdf.strokeColor('#cccccc').lineWidth(1)
  pdf.moveTo(50, pdf.y).lineTo(545, pdf.y).stroke()
  pdf.moveDown(0.5)

  pdf.fontSize(8).fillColor('#666666')
  pdf.text(
    'Disclaimer: This document was generated by ClarionAI to assist with EU AI Act compliance. ' +
    'It should be reviewed and approved by appropriate personnel before being used for regulatory purposes. ' +
    'ClarionAI does not provide legal advice.',
    { align: 'left' }
  )

  pdf.end()

  // Wait for PDF generation to complete
  const pdfBuffer = await new Promise<Buffer>((resolve) => {
    pdf.on('end', () => {
      resolve(Buffer.concat(chunks))
    })
  })

  // Return PDF as download
  const filename = `${document.title.replace(/\s+/g, '_')}_${document.version}.pdf`

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': pdfBuffer.length.toString(),
    },
  })
}
